### ISSUE TITLE
Does DPDK-WiFi support interrupt mode?

### ISSUE THREAD

**Issue by lijieleo** [telematik-tu-ilmenau/DPDK-WiFi#2]

**Comment by thillux** [comment]
The common mode for DPDK is poll mode. We use interrupts only during device setup.

**Comment by lijieleo** [comment]
@thillux thanks for your reply. Noticed ath10k is pcie interface, did you ever try DPDK-WiFi with sdio interface in ARM platform?

**Comment by thillux** [comment]
We haven't used ath10k with SDIO and I am not aware of DPDK supporting SDIO. Our tests ran on PC Engines APU2C4 boards with PCIe.
