### ISSUE TITLE
Could you please provide test-ath10k app?

### ISSUE THREAD

**Issue by lcdtyph** [telematik-tu-ilmenau/DPDK-WiFi#3]
Hi, thanks for this amazing work.

I found [here](https://github.com/telematik-tu-ilmenau/DPDK-WiFi/blob/master/drivers/net/ath10k/Makefile#L36) mentioned the test-ath10k app, but it's missing in the repo. Could you please provide that app or a demo?

Thanks!

**Comment by thillux** [comment]
Hi, I've added a little test-app. Which initializes the ath10k NIC. Please note, that this driver only works on 32-Bit x86 systems, because the card needs 32 Bit buffer addresses.

**Comment by lcdtyph** [comment]
Thank you very much!

**Comment by lcdtyph** [comment]
I saw the app/test-ath10k directory is missing in the source tree, is that matter?

**Comment by thillux** [comment]
Forgot to commit it. Should be fixed now.

**Comment by icpz** [comment]
Thanks!
